site_name: OpenAIRE Algorithm Knowledge Base
site_author: OpenAIRE Mining Team
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
features:
    - navigation.instant

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- Home: index.md
- Impact Measures: impact_measures.md
- Mining Algorithms: mining_algorithms.md
